[package]
name = "cargo_auto_github_lib"
version = "0.1.7"
authors = ["bestia.dev"]
homepage = "https://bestia.dev"
edition = "2018"
description = "Library for cargo-auto `automation tasks written in rust language` with functions for github."
repository = "https://github.com/bestia-dev/cargo_auto_github_lib"
readme = "README.md"
license = "MIT"
keywords = ["rust","cargo-auto"]
categories = ["development-tools::build-utils"]
# publish as a cargo tool. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*",
]

[dependencies]
unwrap = "1.2.1"
octocrab = "0.12.0"
reqwest={version="0.11.4", features=["stream"]}
tokio-util = "0.6.7"
tokio = {version = "1.10.0", features = ["rt","rt-multi-thread","fs"]}
url="2.2.2"
lazy_static = "1.4.0"
cargo_toml = "0.10.0"
