[package]
name = "cargo_auto_github_lib"
version = "0.1.13"
authors = ["bestia.dev"]
homepage = "https://bestia.dev"
edition = "2018"
description = "Library for cargo-auto `automation tasks written in rust language` with functions for github."
repository = "https://github.com/bestia-dev/cargo_auto_github_lib"
readme = "README.md"
license = "MIT"
keywords = ["rust","cargo-auto"]
categories = ["development-tools::build-utils"]
# publish as a cargo tool. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*",
]

[dependencies]
unwrap = "1.2.1"
octocrab = "0.23.0"
reqwest={version="0.11.18", features=["stream"]}
tokio-util = {version = "0.7.8", features = ["codec"]}
tokio = {version = "1.28.2", features = ["rt","rt-multi-thread","fs"]}
url="2.3.1"
lazy_static = "1.4.0"
cargo_toml = "0.15.2"
# http="0.2.9"
# hyper="0.14.26"
